1713728657230	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1713730466857	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1713730466857	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713730466858	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1713730466859	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713730466902	Sync.SyncScheduler	DEBUG	Woke from sleep.
1713730466902	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1713730466902	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1713730466903	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713730468904	Sync.Service	DEBUG	User-Agent: LibreWolf/124.0.2 (Linux x86_64) FxSync/1.126.0.20240401114208.desktop
1713730468904	Sync.Service	INFO	Starting sync at 2024-04-21 22:14:28 in browser session YqOIKg4Bksfq
1713730468904	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713730468906	Sync.Status	INFO	Resetting Status.
1713730468906	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1713730468907	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1713730468907	FirefoxAccounts	DEBUG	getOAuthToken enter
1713730468907	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713730468907	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713730468907	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1713730468908	Sync.SyncAuthManager	INFO	Getting sync key
1713730468908	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1713730468908	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1713730468908	FirefoxAccounts	DEBUG	getOAuthToken enter
1713730468908	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713730468908	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713730468908	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1713730468908	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1713730468909	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713730468910	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713730468910	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1713730468910	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1713730468910	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713730468911	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713730468911	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713730468911	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713730468912	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713730468912	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1713730468912	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1713730468912	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713730468912	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1713730468912	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1713730468918	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
