1713111181940	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1713113950252	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713114352786	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1713114352786	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713114352788	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1713114352789	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713114352825	Sync.SyncScheduler	DEBUG	Woke from sleep.
1713114352825	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1713114352825	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1713114352825	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1713114354829	Sync.Service	DEBUG	User-Agent: LibreWolf/124.0.1 (Linux x86_64) FxSync/1.126.0.20240321230221.desktop
1713114354829	Sync.Service	INFO	Starting sync at 2024-04-14 19:05:54 in browser session 3LlkI0fGcTWh
1713114354830	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1713114354833	Sync.Status	INFO	Resetting Status.
1713114354833	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1713114354834	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1713114354834	FirefoxAccounts	DEBUG	getOAuthToken enter
1713114354834	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713114354834	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713114354835	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1713114354836	Sync.SyncAuthManager	INFO	Getting sync key
1713114354837	Sync.SyncAuthManager	INFO	Getting a sync token from: https://token.services.mozilla.com/1.0/sync/1.5
1713114354837	Sync.SyncAuthManager	DEBUG	Getting a token using OAuth
1713114354837	FirefoxAccounts	DEBUG	getOAuthToken enter
1713114354837	FirefoxAccounts	TRACE	getCachedToken returning cached token
1713114354837	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1713114354837	Services.Common.TokenServerClient	DEBUG	Beginning OAuth token exchange: https://token.services.mozilla.com/1.0/sync/1.5
1713114354837	Services.Common.RESTRequest	DEBUG	GET request to https://token.services.mozilla.com/1.0/sync/1.5
1713114354840	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713114354840	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.sys.mjs :: onStopRequest :: line 478\"  data: no]"}
1713114354841	Services.Common.RESTRequest	DEBUG	GET https://token.services.mozilla.com/1.0/sync/1.5 failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1713114354842	Sync.SyncAuthManager	ERROR	Non-authentication error in _fetchTokenForUser: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713114354842	Sync.Status	DEBUG	Status.login: success.login => error.login.reason.network
1713114354842	Sync.Status	DEBUG	Status.service: success.status_ok => error.login.failed
1713114354843	Sync.SyncAuthManager	ERROR	Failed to fetch a token for authentication: TokenServerClientNetworkError({"error":{}})(resource://services-common/tokenserverclient.sys.mjs:28:36) JS Stack trace: TokenServerClientNetworkError@tokenserverclient.sys.mjs:51:16
_tokenServerExchangeRequest@tokenserverclient.sys.mjs:235:13
1713114354844	FirefoxAccounts	TRACE	not checking freshness of profile as it remains recent
1713114354846	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/206026008/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713114354846	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1713114354846	Sync.Status	DEBUG	Status.service: error.login.failed => error.sync.failed
1713114354846	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1713114354847	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1713114354848	Sync.Telemetry	INFO	Early submission of sync telemetry due to changed IDs/NodeType
1713114354863	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
